name: excel
description: A flutter and dart library for creating, editing and updating excel sheets with compatible both on client and server side.
version: 1.0.2
homepage: https://github.com/kawal7415/excel

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  archive: ^2.0.0
  xml: ^3.0.0

dev_dependencies:
  path: ^1.5.1
  test: ^1.2.0